version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:5173"