source "https://rubygems.org"

gem "rails", "~> 8.0.1"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1.7"
gem "oj_serializers"
gem "pagy", "~> 9.3"
gem "pg", "~> 1.1"
gem "pundit", "~> 2.5"
gem "sorbet", "~> 0.5.11708"
gem "jwt", "~> 2.10", ">= 2.10.1"

gem "rswag-api"
gem "rswag-ui"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "bootsnap", require: false

gem "thruster", require: false

group :development, :test do
  gem "brakeman", require: false
  gem "byebug"
  gem "database_cleaner"
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
  gem "rubocop-rails-omakase", require: false
  gem "ruby-lsp", "~> 0.23.11"
  gem "shoulda-matchers", "~> 5.0"
  gem "rswag-specs"
end
